package com.msyaiful.asuslaptopstore;

import java.util.ArrayList;

public class AsusData {
    public static String[][] data = new String[][]{
            {"Asus VivoBook 14 A405UQ", "Media penyimpanan ganda menjadi salah satu keunggulan produk ini. Oleh Karena itu, milikilah laptop ini jika Anda tidak mau repot menyimpan file melalui cloud atau HDD eksternal. Asus A405UQ dilengkapi  SSD 128 GB dan HDD sebesar 1 TB. Storage SSD bisa diekspansi hingga 512 GB, sedangkan storage HDD-nya bisa diekspansi hingga 2 TB. Komponen RAM DDR4 sebesar 4 GB sudah cukup bila Anda jarang melakukan multitasking. Selanjutnya, CPU Core i5 dapat memenuhi keperluan Anda yang memakai laptop untuk kinerja menengah. Gunakanlah produk ini jika Anda menginginkan laptop dengan baterai yang awet. Asus SuperBattery-nya mampu bertahan tiga kali lebih lama dibandingkan baterai standar lithium-ion silinder. Dengan semua kelebihan itu, laptop ini hanya seharga RP.6.065.000", "https://my-best.id/wp-content/uploads/2018/10/10.-Asus-VivoBook-14-A405UQ-300x300.jpg"},
            {"Asus ROG Strix GL503", "Laptop gaming ini bisa menjadi andalan penikmat game eSport atau game lain dengan durasi permainan yang lama. Teknologi ADC (Anti Dust Cooling) laptop ini bisa menjadi solusi terhadap kebutuhan bermain game secara maraton. Selain itu, teknologi ADC yang telah dipatenkan ini akan mengusir debu dan kotoran agar hardware laptop tetap bersih. Kehadiran dua kipas bertegangan 12 volt berputar lebih cepat daripada kipas konvensional yang bertegangan 5 volt. Di pihak lain, Anda dapat menikmati game dengan kebutuhan visual tinggi berkat tampilan wide-view dengan refresh rate yang tinggi. Berikutnya, posisi panel slide-off di bagian bawah dengan sebuah sekrup akan memudahkan Anda saat melakukan upgrade memory. Laptop ini memiliki harga yang cukup mahal yaitu RP.14.750.000", "https://my-best.id/wp-content/uploads/2018/09/9.-Asus-ROG-Strix-GL503VD-300x200.jpg"},
            {"Asus Transformer Pro T304UA", "Asus Transformer Pro T304 UA adalah laptop 2 in 1 yang dapat difungsikan sebagai tablet. CPU Core i7 menjadikan produk ini mampu melakukan pemrosesan data dengan baik. Tambahan Aksesori berupa Asus Pen akan berguna baik untuk mencatat, menandai foto, maupun menggambar grafis. Jadi, laptop ini cocok untuk menunjang kegiatan profesional saat meeting atau pekerja kreatif saat menggambar. Kebutuhan koneksi bukanlah masalah dengan kehadiran universal dock. Anda dapat terhubung melalui USB tipe C, USB 3.0, HDMI, VGA, RJ45 LAN, serta SD card reader. Tampilan layar laptop ini juga memanjakan penikmat visual akibat kehadiran Asus TruVivid dan teknologi Asus Tru2life. Tambahan pula, resolusi 3K membuat Anda lebih betah berlama-lama saat menonton video. Harga laptop ini juga mahal sebanding dengan kualitasnya yaitu RP.15.750.000", "https://my-best.id/wp-content/uploads/2018/09/8.-Asus-Transformer-Pro-T304UA-300x300.jpg"},
            {"Asus ROG ZEPHYRUS (GX501)", "Laptop ini diklaim oleh Asus sebagai laptop gaming paling tipis. Ukuran body-nya hanya 16,9 mm hingga 17,9 mm dengan berat 2,2 kg saja. Karena itu, Anda bisa menggunakan laptop ini apabila ingin memainkan game di venue yang berbeda-beda. Walaupun demikian, laptop ini tidak mengorbankan performa berkat CPU Core i7 dengan grafis NVIDIA GeForce GTX1080. Salah satu yang menarik dari produk ini adalah pendingin eksklusif Active Aerodynamics System. Hal tersebut membuat laptop tidak mudah panas dan bekerja sunyi kendati berbadan tipis. Saat laptop ini dibuka untuk dipakai, bagian bawahnya akan terangkat untuk menghasilkan sirkulasi udara ekstra hingga 20%. Kini, memainkan game berat di mana pun bukan masalah dengan laptop ini. Harga laptop ini sangatlah mahal yaitu RP.48.000.000", "https://my-best.id/wp-content/uploads/2018/10/7.-Asus-ROG-ZEPHYRUS-GX501-300x169.jpg"},
            {"Asus ZenBook 3 UX390UA", "Asus ZenBook 3 UX390UA adalah laptop segudang prestasi yang telah memenangkan berbagai penghargaan desain terkemuka di dunia. Laptop ini dirancang sehingga menghasilkan bobot hanya 910 gram dengan ketebalan 11.9 mm. Proses pembuatan yang menggunakan material logam campuran aerospace menjadikan produk ini 50% lebih kuat dibandingkan laptop berbahan standar. Performa tinggi laptop ini dihasilkan oleh CPU Core i7 dengan perpaduan SSD sebesar 512 GB. Di samping itu, sebuah sentuhan di bagian touchpad berfungsi sebagai sensor fingerprint guna menjaga keamanan terhadap akses laptop. Ukuran layar sebesar 12,5 inci FHD akan memudahkan Anda yang membutuhkan laptop berkinerja canggih dengan mobilitas tinggi. Laptop ini memiliki harga senilai RP.22.725.000", "https://my-best.id/wp-content/uploads/2018/09/6.-Asus-ZenBook-3-UX390UA-300x300.jpg"},
            {"Asus Transformer Book T101HA", "Tampilan layar laptop ini berukuran 10,1 inci dengan berat 580 gram serta ketebalan 9 mm. Jadi, laptop ini cukup nyaman untuk Anda yang memerlukan laptop untuk dibawa-bawa. Keyboard produk ini bisa Anda lepaskan untuk menjadi tablet sehingga Anda lebih leluasa. Tambahan lagi, baterai yang tahan hingga 11 jam sudah cukup mendukung aktivitas Anda selama di luar ruangan. Produk ini memiliki kinerja cukup untuk kebutuhan standar Anda dengan prosesor Intel QuadCore X5. Fitur USB, micro USB, micro HDMI, dan micro SD membuat konektivitas Anda tetap tersedia selama di luar ruangan. Meskipun begitu, Asus Transformer Book T100HA berharga cukup terjangkau. Pilihlah produk ini jika Anda mencari laptop hybrid yang ekonomis. Laptop ini sangatlah murah yaitu RP.3.899.000", "https://my-best.id/wp-content/uploads/2018/09/5.-Asus-Transformer-Book-T101HA-300x300.jpg"},
            {"Asus ROG Strix GL702ZC", "Kerja berat bukanlah masalah bagi laptop berkinerja tinggi ini berkat prosesor AMD Ryzen 7. CPU ini memungkinkan pekerjaan berat bisa diproses baik saat bermain game atau mengolah multimedia. Sementara itu, ukuran layar yang 17 inci akan cocok untuk memainkan game di rumah. Fitur backlit antighosting-nya mampu mengontrol dengan akurat saat Anda bermain game lho! OG Gaming Center hadir untuk memanjakan pencinta game. Para gamers tentu tidak asing dengan antarmuka yang bisa mengatur permainan dalam satu atap ini. Penggunaan dari grafik AMD Radeon RX580 membuat pengalaman visual saat bermain game berjalan maksimal. Anda bahkan bisa memainkan permainan VR dengan mulus dan bebas stutter. Harga laptop ini adalah RP.20.390.000", "https://my-best.id/wp-content/uploads/2018/09/4.-Asus-ROG-Strix-GL702ZC-300x300.png"},
            {"Asus ZenBook Pro UX550VD", "Produk ini memiliki filosofi tenang di luar, namun kuat di dalam melalui balutan warna black matte. Pekerjaan berat pun bisa dieksekusi oleh prosesor Core i7-7700HQ. Selain itu, kapasitas memory hingga 16 GB mendukung Anda guna melakukan pekerjaan secara multitasking. Rasakanlah juga sensasi melihat layar tanpa gangguan frame dengan NanoEdge display. Performa laptop yang tinggi ini ditunjang oleh dual fan. Akibatnya, temperatur Asus ZenBook Pro UX550VD lebih rendah hingga 2,35o Celsius dibandingkan generasi sebelumnya. Selain itu, kesan mewah juga muncul akibat produk ini mengusung desain unibody dengan finishing metal yang berkilau layaknya sutra. Hal ini tentu mendukung Anda yang ingin tampil profesional dan elegan. Harga laptop ini adalah RP.23.440.000", "https://my-best.id/wp-content/uploads/2018/09/3.-Asus-ZenBook-Pro-UX550VD-300x300.jpg"},
            {"Asus Zenbook 13 UX331UN", "Asus ZenBook 13 UX331UN memiliki ketebalan 13,9 mm dengan berat hanya 1,12 kg. Ukuran tipis tidak menghalangi laptop ini untuk memiliki grafis diskret berupa chip NVIDIA GeForce MX150. Karena itu, Anda bisa menyunting foto, video, atau bermain game dengan penampilan visual yang maksimal. Hal ini jarang terjadi pada laptop ultra-thin yang umumnya tidak memiliki kartu grafis dedicated. Teknologi WiFi master memungkinkan Anda mendapat koneksi internet tercepat dengan lancar. Di samping itu, baterai dengan ketahanan 14 jam memastikan Anda bisa bekerja lama tanpa terhubung ke sumber listrik. Pilihlah laptop ini apabila pekerjaan Anda tergantung dengan kartu grafis seperti editor atau kreator konten, serta untuk Anda yang bekerja dengan mobilitas tinggi. Harga laptop ini adalah RP.14.500.000", "https://my-best.id/wp-content/uploads/2018/09/2.-Asus-Zenbook-13-UX331UN-300x300.jpg"},
            {"Asus VivoBook Flip TP200SA", "Produk ini merupakan laptop model 2-in-1 dengan berat hanya 1,2 kg saja. Bagian keyboard-nya bisa diputar sampai 3600 sehingga lebih fleksibel saat dipakai. Berat ringan dan ukuran layar 11,6 inci menjadikan produk ini mudah dibawa-bawa oleh Anda yang memiliki mobilitas tinggi. Selain itu, tekstur laptop yang antigores tentu mendukung penggunaan di luar ruangan. Prosesor Intel Pentium/Intel Celeron sudah cukup untuk mengerjakan tugas standar, terutama bagi Anda yang tidak membutuhkan laptop dengan kinerja berat. Di bagian media penyimpanan laptop ini dibekali baik dengan SSD maupun eMMC. Selanjutnya, sensitivitas tinggi yang responsif dengan pemakaian sepuluh jari bisa Anda dapatkan di bagian touchpad. Harga laptop ini adalah RP.5.201.000", "https://my-best.id/wp-content/uploads/2018/09/1.-Asus-Transformer-Book-Flip-TP200SA-300x300.jpg"}
    };
    public static ArrayList<Asus> getListData(){
        ArrayList<Asus> list = new ArrayList<>();
        for (String[] aData : data) {
            Asus asus = new Asus();
            asus.setName(aData[0]);
            asus.setFrom(aData[1]);
            asus.setPhoto(aData[2]);
            list.add(asus);
        }
        return list;
    }
}
